### ISSUE TITLE
function to capitalize the first letter of each word in a string.

### ISSUE THREAD

**Issue by swanandapps** [swanandapps/stringy-core#16]
**What is needed:**

Function to capitalize the first letter of each word in a string.

**Where to Code:**

Find the Contribution Station in `lib/textCaseManipulation.js`.

**Contribution Steps:**

1. Create a development branch out of this issue. (Visible on the right column of the issue)
2. Code your function in that branch.
3. Raise a Pull Request to merge that branch into the main branch.

For more clarity, follow the visual guide in `CONTRIBUTE.md`.

**Comment by pratyushbanerjee** [comment]
This function already exists
https://github.com/swanandapps/stringy-core/blob/786fbc72576826d48f2cda5266b25f5b7024ba23/lib/textCaseManipulation.js#L29-L36

**Comment by ssk090** [comment]
I have fixed a potential issue in this issue. Please review my pull request for the same: https://github.com/swanandapps/stringy-core/pull/27
