### ISSUE TITLE
Implement String Shuffle Function

### ISSUE THREAD

**Issue by swanandapps** [swanandapps/stringy-core#3]
### What's Needed:

We're on the lookout for a nifty `shuffleString` function that can mix up characters in a string for us.

### Your Quest:

- **Function Name**: `shuffleString`
- **Goal**: Randomly shuffle the characters in a string.
- **Example**:
  - Input: `'stringy'`
  - Output: `'gtrysin'` (Keep in mind, the output will vary every time!)

### Set Yourself Up for Contributions:

- You need to create a branch out of this issue, that's Step 0.

- Find out all the Steps at [Super Simple Stringy Contribution Guide](CONTRIBUTE.md) 

### Happy Coding!

- Navigate to `lib/textTransformationsAndUtilities.js`

- You wil find **Contribution Station** for `shuffleString` function there and start.

**Comment by mynameishomin** [comment]
can i work on this issue?

**Comment by webdev1903** [comment]
> can i work on this issue?

Of course you can. The best one will be picked by the admin. I mean there's nothing to lose. One more problem solved.
