### ISSUE TITLE
function to Generate Lorem Ipsum Sentences

### ISSUE THREAD

**Issue by swanandapps** [swanandapps/stringy-core#5]
**What is needed:** 

Function to generate random Lorem Ipsum sentences of a specific word count.<br>
**Where to Code:** 

Find the Contribution Station in `textGeneration.js`
<br>**Contribution Steps:**
<br>1. Create a development branch out of this issue. (Visible on the right column of the issue)<br>2. Code your function in that branch.<br>3. Raise a Pull Request to merge that branch into the main branch.<br>

For more clarity, follow the visual guide in `CONTRIBUTE.md`.

**Comment by PedramHaeri** [comment]
Hi I would like to try and fix this issue. could you please assign it to me?

**Comment by ssk090** [comment]
Hey @swanandapps, please checkout the implementation for the same: https://github.com/swanandapps/stringy-core/pull/32
